### ISSUE TITLE
Error when build for Windows

### ISSUE THREAD

**Issue by prsolucoes** [pocoproject/conan-poco#54]
Hi,

I get error when build for Windows:

```
PocoNetSSLWinmdd.lib(SSLException.obj) : error LNK2005: "public: virtual __cdecl Poco::Net::SSLConnectionUnexpectedlyClosedException::~SSLConnectionUnexpectedlyClosedException(void)" (??1SSLConnectionUnexpectedlyClosedException@Net@Poco@@UEAA@XZ) already defined in PocoNetSSLmdd.lib(SSLException.obj)
```

FULL LOG:
https://ci.appveyor.com/project/PauloCoutinho/ezored/builds/26449169#L1611

I don't link anything manually, only include the conan cmake:
https://github.com/ezored/ezored/blob/androidx-kotlin/files/targets/windows_app/cmake/CMakeLists.txt#L16

WHEN IT HAPPENS:
We use poco a lot of time. This problem start now when i use:

```
self.requires('Poco/1.9.2@pocoproject/stable')
self.requires('OpenSSL/1.1.1c@conan/stable')
```

Before the problem it compile normal with:
```
self.requires('Poco/1.9.0@pocoproject/stable')
self.requires('OpenSSL/1.0.2r@conan/stable')
```

CONCLUSION:
The problem is with the new version 1.9.2. 

Can anyone help me?

**Comment by obiltschnig** [comment]
The issue seems to be that you're linking both NetSSL (OpenSSL) and NetSSL_Win. Only one of these must be linked. Not sure yet where this comes from. Could also be related to CMake.

**Comment by prsolucoes** [comment]
Yes, as i sad im not linking anything manually.  Only importing the conan cmake generated. The issue is inside the new version. Something internally is linking it duplicated.

It is very strange. I do the same thing into my other project that is a simple web server using poco and it build with success:
https://github.com/ezored/ezored-server/commit/6f56677200dc8d207807726bcb7c2a362aa56aa4

Do you have any tips?

**Comment by prsolucoes** [comment]
I have built it from my local machine with windows 10 and visual studio 2017 community too with success. But on app veyour the build generate error.

Do you have any tips?

**Comment by prsolucoes** [comment]
Another thing that i discover is that only "PocoNetSSLWinmdd" is duplicated and "PocoNetSSLmdd" is defined first. Nothing more is duplicated.

**Comment by prsolucoes** [comment]
The libs that conan link are (exported from cmake):

```
SQLiteCpp;PocoNetSSLmdd;PocoNetSSLWinmdd;PocoNetmdd;PocoCryptomdd;PocoUtilmdd;PocoRedismdd;PocoFoundationmdd;Iphlpapi;Crypt32;sqlite3;libssld;libcryptod;crypt32;msi;ws2_32;advapi32;user32;gdi32;zlib
```

**Comment by prsolucoes** [comment]
I made a pull request to solve the problem, only need merge now:
https://github.com/pocoproject/conan-poco/pull/56

Thanks.
