### ISSUE TITLE
Conan + MacOs + apple-clang 12.0 => can't include apr/1.7.0

### ISSUE THREAD

**Issue by dhait** [pocoproject/conan-poco#67]
Poco has a dependency on Apache apr/1.7.0. When including the poco conan package in a build, it can't build with the apr due to there being no apr conan package for apple-clang 12.0.

    ERROR: apr/1.7.0: Invalid configuration: apr does not (yet) support apple-clang 12

If we go back to apple-clang 11.0, a whole other host of problems crop up with other libraries.

Looks like Apache apr/1.7.0 is from 2019 with no more recent releases.
I've tried

     Poco:enable_apacheconnector=False

to no avail.
Can this dependency be eliminated?

**Comment by obiltschnig** [comment]
This project is no longer used for building the Conan packages, please see the [Conan Center Index](https://github.com/conan-io/conan-center-index) and #68.
